require File.join(`node --print "require.resolve('react-native/package.json')"`, "../scripts/react_native_pods")
require File.join(`node --print "require.resolve('react-native-unimodules/package.json')"`, "../cocoapods.rb")
require File.join(`node --print "require.resolve('@unimodules/react-native-adapter/package.json')"`, "../scripts/autolinking")

platform :ios, '11.0'

project 'HelloWorld',
  'Debug' => :debug,
  'DebugAdvanced' => :debug,
  'Release' => :release

target 'HelloWorld' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment to opt-in to using Flipper

  # if !ENV['CI']
  #   use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' }, configurations: ['Debug', 'DebugAdvanced'])
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
end
